**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
c=np.random.random((a,b))
print(np.mean(c))
for i in c:
  print(i)


enter the value of a3
enter the value of b2
0.6432220298893817
[0.28886712 0.99043681]
[0.09431271 0.93056637]
[0.98079266 0.57435651]


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
def create_border(a,b):
  global c                      # 🔹 CHANGE 1: allow function to use c
  for i in range(a):            # 🔹 already correct
    for j in range(b):          # 🔹 already correct
      if i==0 or i==a-1 or j==0 or j==b-1:
        c[i][j]=1
      else:
        c[i][j]=0

c = [[0 for j in range(4)] for i in range(4)]   # 🔹 CHANGE 2: proper 2D array
create_border(4,4)

for row in c:                    # 🔹 CHANGE 3: to see output
  print(row)

[1, 1, 1, 1]
[1, 0, 0, 1]
[1, 0, 0, 1]
[1, 1, 1, 1]


In [ ]:
c = [[0 for j in range(4)] for i in range(4)]
print(c)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
a=np.random.random(10)
print(a)

[0.13788602 0.32659161 0.27391342 0.22145452 0.09421685 0.10500203
 0.56721265 0.02261724 0.02935036 0.09021986]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
a=np.zeros((3,4))
a[1,1]=1
a[2,2]=1
a[0,0]=1
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
a=np.zeros((5,5))
for i in range(5):
  for j in range(5):
    a[i][j]=i



In [ ]:
print(a)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
d=[]
point = np.array([2,3])
for i in a:
  d.append(int(np.sqrt(np.sum((point - i)**2))))


In [ ]:
print(d)

[95, 81, 81, 74, 17, 108, 70, 27, 25, 112]


In [ ]:
a=np.random.random((10,2))
a=a*100
print(a)

[[40.59129219 90.63205375]
 [58.20743429 61.96521809]
 [71.50295805 45.45440685]
 [22.12010522 75.03008916]
 [12.89952467 16.32756976]
 [85.90312534 71.30212091]
 [71.33060919 12.89975941]
 [25.36875701 16.71963927]
 [27.07569527  6.51771736]
 [67.0761939  95.20418254]]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
a=np.array([1,2,3,4,-8,-10],np.dtype(float))

In [ ]:
a=a[::-1]

In [ ]:
print(a)

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
a=np.array([1,2,3,4,5])
np.size(a)

5

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
a=np.array([86.03331084 ,37.7285648 ,  48.64908087, 87.16563062, 38.40852563 ,37.20006318])
summation=0
for i in a:
  summation+=np.exp(i)
sigmoid=[]
for i in a:
  sigmoid.append(np.exp(i)/summation)


In [ ]:
sigmoid

[np.float64(0.2437332478419039),
 np.float64(2.5611211391463117e-22),
 np.float64(1.416282828021993e-17),
 np.float64(0.756266752158096),
 np.float64(5.055141972316446e-22),
 np.float64(1.5097491143729272e-22)]

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
a= [[0 ,1 ,2 ,3, 4],
   [5 ,6, 7 ,8, 9]]

b= [[1, 1, 1 ,1, 1],
   [1, 1, 1, 1 ,1]]
c= [[0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
   [0.44581567, 0.13502419, 0.55692335, 0.16479622 ,0.61193593]]
d=np.vstack((a,b,c))
print(d)



[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

###`Q-14:` Subtract the mean of each row from a matrix.

In [3]:
import numpy as np
a=np.random.random((3,3))
a

array([[0.00712106, 0.57934433, 0.51556991],
       [0.12734409, 0.91081924, 0.83385435],
       [0.53041922, 0.46590829, 0.88594291]])

In [4]:
c=np.mean(a,axis=1)
c

array([0.3673451 , 0.62400589, 0.62742348])

In [5]:
a=a-c

In [6]:
a

array([[-0.36022404, -0.04466156, -0.11185357],
       [-0.24000101,  0.28681334,  0.20643087],
       [ 0.16307412, -0.1580976 ,  0.25851944]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [7]:
a

array([[-0.36022404, -0.04466156, -0.11185357],
       [-0.24000101,  0.28681334,  0.20643087],
       [ 0.16307412, -0.1580976 ,  0.25851944]])

In [8]:
a[:,0]=a[:,1]
a[:,1]=a[:,0]

In [9]:
print(a)

[[-0.04466156 -0.04466156 -0.11185357]
 [ 0.28681334  0.28681334  0.20643087]
 [-0.1580976  -0.1580976   0.25851944]]


###`Q-16:` Replace odd elements in arrays with -1.

In [10]:
a=np.random.randint(1,40,25).reshape(5,5)

In [11]:
a

array([[14, 12, 38, 28, 12],
       [ 9, 21, 26,  3, 20],
       [27, 34,  4, 39, 16],
       [ 9, 15, 26, 36, 22],
       [31, 38, 27, 34, 17]])

In [14]:
a[~(a%2==0)]=-1

In [15]:
a

array([[14, 12, 38, 28, 12],
       [-1, -1, 26, -1, 20],
       [-1, 34,  4, -1, 16],
       [-1, -1, 26, 36, 22],
       [-1, 38, -1, 34, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [17]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
np.maximum(a,b)

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [19]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1512, 2504, 7440, 4133, 8890],
       [ 213, 6964, 3690, 1122, 2348],
       [7258, 4508, 8297, 5379, 6208],
       [2785, 3089,    1, 6605, 2015],
       [5285, 8451, 5248, 3084, 8868],
       [5696, 5527, 4059, 9159, 5469],
       [4889, 9837, 8256, 9985, 4653],
       [2850, 1451, 3912, 3771, 2526]])

In [20]:
arr1

array([[1512, 2504, 7440, 4133, 8890],
       [ 213, 6964, 3690, 1122, 2348],
       [7258, 4508, 8297, 5379, 6208],
       [2785, 3089,    1, 6605, 2015],
       [5285, 8451, 5248, 3084, 8868],
       [5696, 5527, 4059, 9159, 5469],
       [4889, 9837, 8256, 9985, 4653],
       [2850, 1451, 3912, 3771, 2526]])

In [22]:
##solution of 1
arr1[:,0::2]


array([[1512, 7440, 8890],
       [ 213, 3690, 2348],
       [7258, 8297, 6208],
       [2785,    1, 2015],
       [5285, 5248, 8868],
       [5696, 4059, 5469],
       [4889, 8256, 4653],
       [2850, 3912, 2526]])

In [23]:
##normalize the error
normalized=(arr1-np.min(arr1))/np.max(arr1)-np.min(arr1)

In [24]:
normalized

array([[-8.48673010e-01, -7.49323986e-01, -2.54982474e-01,
        -5.86179269e-01, -1.09764647e-01],
       [-9.78768152e-01, -3.02653981e-01, -6.30545819e-01,
        -8.87731597e-01, -7.64947421e-01],
       [-2.73209815e-01, -5.48622934e-01, -1.69153731e-01,
        -4.61392088e-01, -3.78367551e-01],
       [-7.21181773e-01, -6.90736104e-01, -1.00000000e+00,
        -3.38607912e-01, -7.98297446e-01],
       [-4.70806209e-01, -1.53730596e-01, -4.74511768e-01,
        -6.91236855e-01, -1.11967952e-01],
       [-4.29644467e-01, -4.46569855e-01, -5.93590386e-01,
        -8.28242364e-02, -4.52378568e-01],
       [-5.10465699e-01, -1.49223836e-02, -1.73259890e-01,
        -1.00150225e-04, -5.34101152e-01],
       [-7.14672008e-01, -8.54782173e-01, -6.08312469e-01,
        -6.22433650e-01, -7.47120681e-01]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [41]:
def nthlargest(arr,n):

  temp=np.sort(arr)
  temp=temp[::-1]

  for i in range(n):
    if(i==n-1):
      return temp[i]


In [44]:
arr=np.array([12,34,40,7,1,0])
print(nthlargest(arr,1))

40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [50]:
out = np.concatenate((np.repeat(a, 3), np.tile(a, 3)))
print(out)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [51]:
np.tile(a,2)

array([1, 2, 3, 1, 2, 3])